// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.3
// source: protos/mj/mj.proto

package proto_mj

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BeginGameNot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeginGameNot) Reset() {
	*x = BeginGameNot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginGameNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginGameNot) ProtoMessage() {}

func (x *BeginGameNot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginGameNot.ProtoReflect.Descriptor instead.
func (*BeginGameNot) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{0}
}

type SetDealerNot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dices []int32 `protobuf:"varint,1,rep,packed,name=dices,proto3" json:"dices,omitempty"`
	Uid   string  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SetDealerNot) Reset() {
	*x = SetDealerNot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDealerNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDealerNot) ProtoMessage() {}

func (x *SetDealerNot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDealerNot.ProtoReflect.Descriptor instead.
func (*SetDealerNot) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{1}
}

func (x *SetDealerNot) GetDices() []int32 {
	if x != nil {
		return x.Dices
	}
	return nil
}

func (x *SetDealerNot) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type HandCardsNot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandCards []int32 `protobuf:"varint,1,rep,packed,name=handCards,proto3" json:"handCards,omitempty"`
}

func (x *HandCardsNot) Reset() {
	*x = HandCardsNot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandCardsNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandCardsNot) ProtoMessage() {}

func (x *HandCardsNot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandCardsNot.ProtoReflect.Descriptor instead.
func (*HandCardsNot) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{2}
}

func (x *HandCardsNot) GetHandCards() []int32 {
	if x != nil {
		return x.HandCards
	}
	return nil
}

type OperateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCodes []int32 `protobuf:"varint,1,rep,packed,name=opCodes,proto3" json:"opCodes,omitempty"`
}

func (x *OperateReq) Reset() {
	*x = OperateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateReq) ProtoMessage() {}

func (x *OperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateReq.ProtoReflect.Descriptor instead.
func (*OperateReq) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{3}
}

func (x *OperateReq) GetOpCodes() []int32 {
	if x != nil {
		return x.OpCodes
	}
	return nil
}

type OperateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCode int32   `protobuf:"varint,1,opt,name=opCode,proto3" json:"opCode,omitempty"`
	Cards  []int32 `protobuf:"varint,2,rep,packed,name=cards,proto3" json:"cards,omitempty"`
}

func (x *OperateRes) Reset() {
	*x = OperateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRes) ProtoMessage() {}

func (x *OperateRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRes.ProtoReflect.Descriptor instead.
func (*OperateRes) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{4}
}

func (x *OperateRes) GetOpCode() int32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *OperateRes) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type OperateNot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChairId int32   `protobuf:"varint,1,opt,name=chairId,proto3" json:"chairId,omitempty"`
	OpCode  int32   `protobuf:"varint,2,opt,name=opCode,proto3" json:"opCode,omitempty"`
	Cards   []int32 `protobuf:"varint,3,rep,packed,name=cards,proto3" json:"cards,omitempty"`
}

func (x *OperateNot) Reset() {
	*x = OperateNot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateNot) ProtoMessage() {}

func (x *OperateNot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateNot.ProtoReflect.Descriptor instead.
func (*OperateNot) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{5}
}

func (x *OperateNot) GetChairId() int32 {
	if x != nil {
		return x.ChairId
	}
	return 0
}

func (x *OperateNot) GetOpCode() int32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *OperateNot) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadyReq) Reset() {
	*x = ReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyReq) ProtoMessage() {}

func (x *ReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyReq.ProtoReflect.Descriptor instead.
func (*ReadyReq) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{6}
}

type ReadyNot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReadyNot) Reset() {
	*x = ReadyNot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mj_mj_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyNot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyNot) ProtoMessage() {}

func (x *ReadyNot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mj_mj_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyNot.ProtoReflect.Descriptor instead.
func (*ReadyNot) Descriptor() ([]byte, []int) {
	return file_protos_mj_mj_proto_rawDescGZIP(), []int{7}
}

func (x *ReadyNot) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_protos_mj_mj_proto protoreflect.FileDescriptor

var file_protos_mj_mj_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6a, 0x2f, 0x6d, 0x6a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6a, 0x22, 0x0e,
	0x0a, 0x0c, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x22, 0x36,
	0x0a, 0x0c, 0x53, 0x65, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x64,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x4e, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x22, 0x26, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x0a,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x0a,
	0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x4e, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_mj_mj_proto_rawDescOnce sync.Once
	file_protos_mj_mj_proto_rawDescData = file_protos_mj_mj_proto_rawDesc
)

func file_protos_mj_mj_proto_rawDescGZIP() []byte {
	file_protos_mj_mj_proto_rawDescOnce.Do(func() {
		file_protos_mj_mj_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_mj_mj_proto_rawDescData)
	})
	return file_protos_mj_mj_proto_rawDescData
}

var file_protos_mj_mj_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_mj_mj_proto_goTypes = []interface{}{
	(*BeginGameNot)(nil), // 0: proto.mj.BeginGameNot
	(*SetDealerNot)(nil), // 1: proto.mj.SetDealerNot
	(*HandCardsNot)(nil), // 2: proto.mj.HandCardsNot
	(*OperateReq)(nil),   // 3: proto.mj.OperateReq
	(*OperateRes)(nil),   // 4: proto.mj.OperateRes
	(*OperateNot)(nil),   // 5: proto.mj.OperateNot
	(*ReadyReq)(nil),     // 6: proto.mj.ReadyReq
	(*ReadyNot)(nil),     // 7: proto.mj.ReadyNot
}
var file_protos_mj_mj_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_mj_mj_proto_init() }
func file_protos_mj_mj_proto_init() {
	if File_protos_mj_mj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_mj_mj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginGameNot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDealerNot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandCardsNot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateNot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mj_mj_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyNot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_mj_mj_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_mj_mj_proto_goTypes,
		DependencyIndexes: file_protos_mj_mj_proto_depIdxs,
		MessageInfos:      file_protos_mj_mj_proto_msgTypes,
	}.Build()
	File_protos_mj_mj_proto = out.File
	file_protos_mj_mj_proto_rawDesc = nil
	file_protos_mj_mj_proto_goTypes = nil
	file_protos_mj_mj_proto_depIdxs = nil
}
